# /**:
#   ros__parameters:
#     input_frame: "base_link"
#     output_frame: "base_link"
#     min_x: -60.0
#     max_x: 60.0
#     min_y: -60.0
#     max_y: 60.0
#     min_z: -30.0
#     max_z: 60.0
#     negative: False
/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    min_x: -100.0
    max_x: 100.0
    min_y: -100.0
    max_y: 100.0
    min_z: -30.0
    max_z: 80.0
    negative: False
